version: "3"

services:
  jupyter:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: jupyter-lab --allow-root --ip=*
    ports:
      - "8080:8888"
    volumes:
      - "${PWD}/src:/code"
